server:
  port: 8900
zookeeper:
  server: 127.0.0.1:2181
  namespace: grpc-zk             #zk连接认证 username:passwd
  sessionTimeoutMs: 60000     #会话超时时间(毫秒),连接断开后，其它客户端还能请到临时节点的时间(还受tickTime设置影响[2倍-20倍])
  connectionTimeoutMs: 5000   #连接创建超时时间(毫秒)
  maxRetries: 1               #最大重试次数
  baseSleepTimeMs: 1000       #初始sleep时间(毫秒)
grpc:
  server:
    host: 127.0.0.1
    port: 9099
  client:
    zkAddress: zk://127.0.0.1:2181
    keepAliveTime: 10
    keepAliveTimeout: 3
    keepAliveWithoutCalls: true
    loadBalancingPolicy: round_robin
    idleTimeout: 30
    maxRetryAttempts: 3